Create .taskcluster.yml
taskcluster/taskcluster-lib-monitor pull request #45
Opened 2016-09-19 22:59 UTC by owlishDeveloper

A configuration file from Outreachy applicant (ireneOwl on IRC).

2016-09-19 23:12 UTC, owlishDeveloper commented
@imbstack please review!

2016-09-19 23:43 UTC, owlishDeveloper commented
@owlishDeveloper

2016-09-19 23:50 UTC, imbstack commented on .taskcluster.yml
> +    image: "quay.io/mrrrgn/ubuntu-ci:0.0.1"
Unfortunately this line won't be very good anymore (I need to update the docs to reflect this!).

2016-09-19 23:52 UTC, imbstack commented on .taskcluster.yml
> +    command:
And similarly this command will need to be updated.

This command and the `image` associated with it for the above comment is best taken from https://github.com/taskcluster/taskcluster-github/blob/master/.taskcluster.yml#L24-L28

This is just due to bit-rot on the part of the `quay.io/mrrrgn` image. The fact that the command in this version is so much longer is annoying, but perhaps we can figure out a way to fix it soon!

2016-09-19 23:52 UTC, imbstack requested changes
This is looking very nice! Thanks for the PR.

2016-09-20 00:24 UTC, owlishDeveloper commented on .taskcluster.yml
> +    image: "quay.io/mrrrgn/ubuntu-ci:0.0.1"
done in new commit!

2016-09-20 00:24 UTC, owlishDeveloper commented on .taskcluster.yml
> +    command:
Done as well!

2016-09-20 00:53 UTC, imbstack approved these changes

2016-09-20 00:54 UTC, imbstack commented
This looks great! r+

I'll merge now.

2016-09-20 00:54 UTC, merged